var PS={};(function(a){a.concatString=function(b){return function(a){return b+a}};a.concatArray=function(b){return function(a){return b.concat(a)}};a.topInt=2147483647;a.bottomInt=-2147483648;a.showIntImpl=function(b){return b.toString()};a.showNumberImpl=function(b){return b===(b|0)?b+".0":b.toString()}})(PS.Prelude=PS.Prelude||{});
(function(a){var b=PS.Prelude,c=function(b){this.compose=b},d=function(b,a){this["__superclass_Prelude.Semigroupoid_0"]=b;this.id=a},e=function(b){this.append=b},f=function(b,a){this.bottom=b;this.top=a},g=function(b){this.show=b},h={},k=new g(b.showNumberImpl),m=new g(b.showIntImpl),n=new c(function(b){return function(a){return function(c){return b(a(c))}}}),p=new e(b.concatString),l=new e(b.concatArray),r=function(b){return b.pure},t=function(b){return function(a){return b}},v=new d(function(){return n},
function(b){return b}),b=new f(b.bottomInt,b.topInt),w=function(b){return b.bind},x=function(b){return b.apply};a.Show=g;a.Bounded=f;a.Semigroup=e;a.Monad=function(b,a){this["__superclass_Prelude.Applicative_0"]=b;this["__superclass_Prelude.Bind_1"]=a};a.Bind=function(b,a){this["__superclass_Prelude.Apply_0"]=b;this.bind=a};a.Applicative=function(b,a){this["__superclass_Prelude.Apply_0"]=b;this.pure=a};a.Apply=function(b,a){this["__superclass_Prelude.Functor_0"]=b;this.apply=a};a.Functor=function(b){this.map=
b};a.Category=d;a.Semigroupoid=c;a.show=function(b){return b.show};a.bottom=function(b){return b.bottom};a.top=function(b){return b.top};a["<>"]=function(b){return b.append};a.append=function(b){return b.append};a.ap=function(b){return function(a){return function(c){return w(b["__superclass_Prelude.Bind_1"]())(a)(function(a){return w(b["__superclass_Prelude.Bind_1"]())(c)(function(c){return r(b["__superclass_Prelude.Applicative_0"]())(a(c))})})}}};a["return"]=r;a.bind=w;a.liftA1=function(b){return function(a){return function(c){return x(b["__superclass_Prelude.Apply_0"]())((0,b.pure)(a))(c)}}};
a.pure=function(b){return b.pure};a["<*>"]=x;a.apply=function(b){return b.apply};a["void"]=function(b){return function(a){return(0,b.map)(t(h))(a)}};a["<$>"]=function(b){return b.map};a.map=function(b){return b.map};a.id=function(b){return b.id};a.compose=function(b){return b.compose};a.otherwise=!0;a["const"]=t;a.flip=function(b){return function(a){return function(c){return b(c)(a)}}};a.unit=h;a.semigroupoidFn=n;a.categoryFn=v;a.semigroupString=p;a.semigroupArray=l;a.boundedInt=b;a.showInt=m;a.showNumber=
k})(PS.Prelude=PS.Prelude||{});(function(a){a.fromNumberImpl=function(b){return function(a){return function(d){return(d|0)===d?b(d):a}}};a.toNumber=function(b){return b}})(PS["Data.Int"]=PS["Data.Int"]||{});(function(a){var b=PS.Prelude,c=function(b,a){this["__superclass_Prelude.Semigroup_0"]=b;this.mempty=a},d=new c(function(){return b.semigroupString},"");a.Monoid=c;a.mempty=function(b){return b.mempty};a.monoidString=d})(PS["Data.Monoid"]=PS["Data.Monoid"]||{});
(function(a){var b=function(){function b(){}b.value=new b;return b}(),c=function(){function b(a){this.value0=a}b.create=function(a){return new b(a)};return b}();a.Nothing=b;a.Just=c})(PS["Data.Maybe"]=PS["Data.Maybe"]||{});(function(a){a.unsafeThrow=function(b){throw Error(b);}})(PS["Data.Maybe.Unsafe"]=PS["Data.Maybe.Unsafe"]||{});
(function(a){var b=PS["Data.Maybe.Unsafe"],c=PS["Data.Maybe"];a.fromJust=function(a){if(a instanceof c.Just)return a.value0;if(a instanceof c.Nothing)return b.unsafeThrow("Data.Maybe.Unsafe.fromJust called on Nothing");throw Error("Failed pattern match at Data.Maybe.Unsafe line 11, column 1 - line 12, column 1: "+[a.constructor.name]);}})(PS["Data.Maybe.Unsafe"]=PS["Data.Maybe.Unsafe"]||{});(function(a){a.round=Math.round;a.pi=Math.PI})(PS.Math=PS.Math||{});
(function(a){var b=PS.Math;a.pi=b.pi;a.round=b.round})(PS.Math=PS.Math||{});
(function(a){var b=PS["Data.Int"],c=PS.Prelude,d=PS["Data.Maybe"],e=PS["Data.Maybe.Unsafe"],f=PS.Math,g=b.fromNumberImpl(d.Just.create)(d.Nothing.value);a.round=function(a){a=f.round(a);if(a>=b.toNumber(c.top(c.boundedInt)))a=c.top(c.boundedInt);else if(a<=b.toNumber(c.bottom(c.boundedInt)))a=c.bottom(c.boundedInt);else if(c.otherwise)a=e.fromJust(g(a));else throw Error("Failed pattern match at Data.Int line 49, column 1 - line 56, column 1: "+[a.constructor.name]);return a};a.fromNumber=g;a.toNumber=
b.toNumber})(PS["Data.Int"]=PS["Data.Int"]||{});
(function(a){var b=PS.Prelude,c=PS["Data.Int"],d=function(){function b(a,c,d,e){this.value0=a;this.value1=c;this.value2=d;this.value3=e}b.create=function(a){return function(c){return function(d){return function(k){return new b(a,c,d,k)}}}};return b}();a.cssStringHSLA=function(a){var d=function(a){return b.show(b.showNumber)(c.toNumber(c.round(100*a))/100)},g=d(100*a.value1)+"%",h=d(100*a.value2)+"%",d=d(a.value0),k=b.show(b.showNumber)(a.value3);if(a=1===a.value3)return"hsl("+(d+(", "+(g+(", "+(h+
")")))));if(!a)return"hsla("+(d+(", "+(g+(", "+(h+(", "+(k+")")))))));throw Error("Failed pattern match at Color line 206, column 3 - line 210, column 3: "+[a.constructor.name]);};a.hsl=function(b){return function(a){return function(c){return new d(b,a,c,1)}}}})(PS.Color=PS.Color||{});
(function(a){var b=PS.Prelude;a.lift3=function(a){return function(d){return function(e){return function(f){return function(g){return b["<*>"](a)(b["<*>"](a)(b["<$>"](a["__superclass_Prelude.Functor_0"]())(d)(e))(f))(g)}}}}};a.lift2=function(a){return function(d){return function(e){return function(f){return b["<*>"](a)(b["<$>"](a["__superclass_Prelude.Functor_0"]())(d)(e))(f)}}}};a["*>"]=function(a){return function(d){return function(e){return b["<*>"](a)(b["<$>"](a["__superclass_Prelude.Functor_0"]())(b["const"](b.id(b.categoryFn)))(d))(e)}}}})(PS["Control.Apply"]=
PS["Control.Apply"]||{});(function(a){var b=PS.Prelude;a.when=function(a){return function(d){return function(e){if(d)return e;if(!d)return b["return"](a["__superclass_Prelude.Applicative_0"]())(b.unit);throw Error("Failed pattern match at Control.Monad line 9, column 1 - line 10, column 1: "+[d.constructor.name,e.constructor.name]);}}}})(PS["Control.Monad"]=PS["Control.Monad"]||{});
(function(a){a.returnE=function(b){return function(){return b}};a.bindE=function(b){return function(a){return function(){return a(b())()}}}})(PS["Control.Monad.Eff"]=PS["Control.Monad.Eff"]||{});
(function(a){var b=PS["Control.Monad.Eff"],c=PS.Prelude,d=new c.Monad(function(){return g},function(){return e}),e=new c.Bind(function(){return f},b.bindE),f=new c.Apply(function(){return h},c.ap(d)),g=new c.Applicative(function(){return f},b.returnE),h=new c.Functor(c.liftA1(g));a.functorEff=h;a.applyEff=f;a.applicativeEff=g;a.bindEff=e;a.monadEff=d})(PS["Control.Monad.Eff"]=PS["Control.Monad.Eff"]||{});
(function(a){a.foldrArray=function(b){return function(a){return function(d){for(var e=a,f=d.length-1;0<=f;f--)e=b(d[f])(e);return e}}};a.foldlArray=function(b){return function(a){return function(d){for(var e=a,f=d.length,g=0;g<f;g++)e=b(e)(d[g]);return e}}}})(PS["Data.Foldable"]=PS["Data.Foldable"]||{});
(function(a){var b=PS["Data.Foldable"],c=PS.Prelude,d=PS["Control.Apply"],e=PS["Data.Maybe"],f=PS["Data.Monoid"],g=function(b,a,c){this.foldMap=b;this.foldl=a;this.foldr=c},h=function(b){return function(a){return function(e){return(0,a.foldr)(function(a){return d["*>"](b["__superclass_Prelude.Apply_0"]())(e(a))})(c.pure(b)(c.unit))}}},k=new g(function(b){return function(a){return function(c){if(c instanceof e.Nothing)return f.mempty(b);if(c instanceof e.Just)return a(c.value0);throw Error("Failed pattern match at Data.Foldable line 108, column 3 - line 109, column 3: "+
[a.constructor.name,c.constructor.name]);}}},function(b){return function(a){return function(c){if(c instanceof e.Nothing)return a;if(c instanceof e.Just)return b(a)(c.value0);throw Error("Failed pattern match at Data.Foldable line 106, column 3 - line 107, column 3: "+[b.constructor.name,a.constructor.name,c.constructor.name]);}}},function(b){return function(a){return function(c){if(c instanceof e.Nothing)return a;if(c instanceof e.Just)return b(c.value0)(a);throw Error("Failed pattern match at Data.Foldable line 104, column 3 - line 105, column 3: "+
[b.constructor.name,a.constructor.name,c.constructor.name]);}}}),m=function(b){return function(a){return function(d){return function(e){return(0,b.foldr)(function(b){return function(e){return c["<>"](a["__superclass_Prelude.Semigroup_0"]())(d(b))(e)}})(f.mempty(a))(e)}}}},n=new g(function(b){return m(n)(b)},b.foldlArray,b.foldrArray);a.Foldable=g;a.intercalate=function(b){return function(a){return function(d){return function(e){return(0,b.foldl)(function(b){return function(e){return b.init?{init:!1,
acc:e}:{init:!1,acc:c["<>"](a["__superclass_Prelude.Semigroup_0"]())(b.acc)(c["<>"](a["__superclass_Prelude.Semigroup_0"]())(d)(e))}}})({init:!0,acc:f.mempty(a)})(e).acc}}}};a.for_=function(b){return function(a){return c.flip(h(b)(a))}};a.traverse_=h;a.fold=function(b){return function(a){return(0,b.foldMap)(a)(c.id(c.categoryFn))}};a.foldMapDefaultR=m;a.foldMap=function(b){return b.foldMap};a.foldl=function(b){return b.foldl};a.foldr=function(b){return b.foldr};a.foldableArray=n;a.foldableMaybe=k})(PS["Data.Foldable"]=
PS["Data.Foldable"]||{});
(function(a){var b=PS.Prelude,c=PS["Data.Foldable"],d=PS["Data.Monoid"],e=function(){function b(){}b.value=new b;return b}(),f=function(){function b(a,c){this.value0=a;this.value1=c}b.create=function(a){return function(c){return new b(a,c)}};return b}(),g=new c.Foldable(function(a){return function(e){return c.foldl(g)(function(c){return function(d){return b.append(a["__superclass_Prelude.Semigroup_0"]())(c)(e(d))}})(d.mempty(a))}},function(){return function(b){return function(a){return function(c){var d=b,
g=a,l=c;a:for(;;){if(l instanceof e)return g;if(l instanceof f){c=d;g=d(g)(l.value0);l=l.value1;d=c;continue a}throw Error("Failed pattern match at Data.List line 767, column 3 - line 771, column 3: "+[d.constructor.name,g.constructor.name,l.constructor.name]);}}}}}(),function(b){return function(a){return function(d){if(d instanceof e)return a;if(d instanceof f)return b(d.value0)(c.foldr(g)(b)(a)(d.value1));throw Error("Failed pattern match at Data.List line 765, column 3 - line 766, column 3: "+
[b.constructor.name,a.constructor.name,d.constructor.name]);}}});a.Nil=e;a.Cons=f;a.foldableList=g})(PS["Data.List"]=PS["Data.List"]||{});
(function(a){function b(b,a,e,f){return function(g){return function(h){return function(k){return function(){var m;void 0===window.flareID&&(window.flareID=0);window.flareID+=1;m="flare-component-"+window.flareID.toString();var n=a(h);n.className="flare-input-"+b;n.id=m;var p=document.createElement("div");p.className="flare-input";if(""!==g){var l=document.createElement("label");l.htmlFor=m;l.appendChild(document.createTextNode(g));p.appendChild(l)}p.appendChild(n);n.addEventListener(e,function(b){b=
f(b.target,h);k(b)()});return p}}}}}a.renderString=function(b){return function(a){return function(){document.getElementById(b).innerHTML=a}}};a.removeChildren=function(b){return function(){for(var a=document.getElementById(b);a.firstChild;)a.removeChild(a.firstChild)}};a.appendComponent=function(b){return function(a){return function(){document.getElementById(b).appendChild(a)}}};a.cNumberRange=function(a){return function(d){return function(e){return function(f){return b("number-"+a,function(b){var h=
document.createElement("input");h.type=a;h.min=d.toString();h.max=e.toString();h.step=f.toString();h.value=b.toString();return h},"input",function(b,a){var c=parseFloat(b.value);return isNaN(c)?a:c<d?d:c>e?e:c})}}}};a.cIntRange=function(a){return function(d){return function(e){return b("int-"+a,function(b){var g=document.createElement("input");g.type=a;g.min=d.toString();g.max=e.toString();g.step="1";g.value=b.toString();return g},"input",function(b,a){var c=parseInt(b.value,10);return isNaN(c)?a:
c<d?d:c>e?e:c})}}}})(PS.Flare=PS.Flare||{});
(function(a){a.constant=function(b){var a=[],d=b;return{subscribe:function(b){a.push(b);b(d)},get:function(){return d},set:function(b){d=b;a.forEach(function(a){a(b)})}}};a.mapSigP=function(b){return function(a){return function(d){var e=b(a(d.get()));d.subscribe(function(b){e.set(a(b))});return e}}};a.applySigP=function(b){return function(a){return function(d){var e=b(a.get()(d.get())),f=function(){e.set(a.get()(d.get()))};a.subscribe(f);d.subscribe(f);return e}}};a.runSignal=function(b){return function(){b.subscribe(function(b){b()});
return{}}}})(PS.Signal=PS.Signal||{});(function(a){var b=PS.Signal,c=PS.Prelude,d=b.mapSigP(b.constant),e=new c.Functor(d),d=b.applySigP(b.constant),c=new c.Apply(function(){return e},d);a.functorSignal=e;a.applySignal=c;a.runSignal=b.runSignal;a.constant=b.constant})(PS.Signal=PS.Signal||{});
(function(a){a.channelP=function(b){return function(a){return function(){return b(a)}}};a.sendP=function(b,a){return function(a){return function(){b.set(a)}}};a.subscribe=function(b){return b}})(PS["Signal.Channel"]=PS["Signal.Channel"]||{});(function(a){var b=PS["Signal.Channel"],c=b.sendP,d=b.channelP(PS.Signal.constant);a.send=c;a.channel=d;a.subscribe=b.subscribe})(PS["Signal.Channel"]=PS["Signal.Channel"]||{});
(function(a){var b=PS.Flare,c=PS.Prelude,d=PS["Data.Foldable"],e=PS["Control.Apply"],f=PS["Control.Monad.Eff"],g=PS.Signal,h=PS["Signal.Channel"],k=function(){function b(a,c){this.value0=a;this.value1=c}b.create=function(a){return function(c){return new b(a,c)}};return b}(),m=function(b){return b},n=function(a){return function(e){return function(h){return function(){var l=h();b.removeChildren(a)();d.traverse_(f.applicativeEff)(d.foldableArray)(b.appendComponent(a))(l.value0)();return g.runSignal(c.map(g.functorSignal)(e)(l.value1))()}}}},
p=new c.Functor(function(b){return function(a){return new k(a.value0,c.map(g.functorSignal)(b)(a.value1))}}),l=new c.Functor(function(b){return function(a){return m(c.map(f.functorEff)(c.map(p)(b))(a))}}),r=function(b){return function(a){return function(c){return m(function(){var d=h.channel(c)(),e=b(a)(c)(h.send(d))(),d=h.subscribe(d);return new k([e],d)})}}},t=new c.Apply(function(){return p},function(b){return function(a){return new k(c["<>"](c.semigroupArray)(b.value0)(a.value0),c["<*>"](g.applySignal)(b.value1)(a.value1))}}),
v=new c.Apply(function(){return l},function(b){return function(a){return m(e.lift2(f.applyEff)(c.apply(t))(b)(a))}});a.runFlare=function(a){return function(c){return n(a)(b.renderString(c))}};a.runFlareWith=n;a["int"]=function(a){return r(b.cIntRange("number")(c.bottom(c.boundedInt))(c.top(c.boundedInt)))(a)};a.numberSlider=function(a){return function(c){return function(d){return function(e){return function(g){return r(b.cNumberRange("range")(c)(d)(e))(a)(g)}}}}};a.functorFlare=p;a.applyFlare=t;a.functorUI=
l;a.applyUI=v})(PS.Flare=PS.Flare||{});
(function(a){a.getCanvasElementByIdImpl=function(b,a,d){return function(){var e=document.getElementById(b);return e&&e instanceof HTMLCanvasElement?a(e):d}};a.getContext2D=function(b){return function(){return b.getContext("2d")}};a.getCanvasWidth=function(b){return function(){return b.width}};a.getCanvasHeight=function(b){return function(){return b.height}};a.setLineWidth=function(b){return function(a){return function(){a.lineWidth=b;return a}}};a.setFillStyle=function(b){return function(a){return function(){a.fillStyle=
b;return a}}};a.setStrokeStyle=function(a){return function(c){return function(){c.strokeStyle=a;return c}}};a.setShadowColor=function(a){return function(c){return function(){c.shadowColor=a;return c}}};a.setShadowBlur=function(a){return function(c){return function(){c.shadowBlur=a;return c}}};a.setShadowOffsetX=function(a){return function(c){return function(){c.shadowOffsetX=a;return c}}};a.setShadowOffsetY=function(a){return function(c){return function(){c.shadowOffsetY=a;return c}}};a.beginPath=
function(a){return function(){a.beginPath();return a}};a.stroke=function(a){return function(){a.stroke();return a}};a.fill=function(a){return function(){a.fill();return a}};a.clip=function(a){return function(){a.clip();return a}};a.lineTo=function(a){return function(c){return function(d){return function(){a.lineTo(c,d);return a}}}};a.moveTo=function(a){return function(c){return function(d){return function(){a.moveTo(c,d);return a}}}};a.closePath=function(a){return function(){a.closePath();return a}};
a.arc=function(a){return function(c){return function(){a.arc(c.x,c.y,c.r,c.start,c.end);return a}}};a.rect=function(a){return function(c){return function(){a.rect(c.x,c.y,c.w,c.h);return a}}};a.scale=function(a){return function(c){return function(){c.scale(a.scaleX,a.scaleY);return c}}};a.rotate=function(a){return function(c){return function(){c.rotate(a);return c}}};a.translate=function(a){return function(c){return function(){c.translate(a.translateX,a.translateY);return c}}};a.clearRect=function(a){return function(c){return function(){a.clearRect(c.x,
c.y,c.w,c.h);return a}}};a.font=function(a){return function(){return a.font}};a.setFont=function(a){return function(c){return function(){c.font=a;return c}}};a.fillText=function(a){return function(c){return function(d){return function(e){return function(){a.fillText(c,d,e);return a}}}}};a.save=function(a){return function(){a.save();return a}};a.restore=function(a){return function(){a.restore();return a}}})(PS["Graphics.Canvas"]=PS["Graphics.Canvas"]||{});
(function(a){var b=PS["Graphics.Canvas"],c=PS["Data.Maybe"];a.withContext=function(a){return function(c){return function(){b.save(a)();var f=c();b.restore(a)();return f}}};a.fillPath=function(a){return function(c){return function(){b.beginPath(a)();var f=c();b.fill(a)();return f}}};a.strokePath=function(a){return function(c){return function(){b.beginPath(a)();var f=c();b.stroke(a)();return f}}};a.getCanvasElementById=function(a){return b.getCanvasElementByIdImpl(a,c.Just.create,c.Nothing.value)};
a.fillText=b.fillText;a.setFont=b.setFont;a.translate=b.translate;a.rotate=b.rotate;a.scale=b.scale;a.clearRect=b.clearRect;a.rect=b.rect;a.arc=b.arc;a.closePath=b.closePath;a.moveTo=b.moveTo;a.lineTo=b.lineTo;a.clip=b.clip;a.setShadowColor=b.setShadowColor;a.setShadowOffsetY=b.setShadowOffsetY;a.setShadowOffsetX=b.setShadowOffsetX;a.setShadowBlur=b.setShadowBlur;a.setStrokeStyle=b.setStrokeStyle;a.setFillStyle=b.setFillStyle;a.setLineWidth=b.setLineWidth;a.getCanvasHeight=b.getCanvasHeight;a.getCanvasWidth=
b.getCanvasWidth;a.getContext2D=b.getContext2D})(PS["Graphics.Canvas"]=PS["Graphics.Canvas"]||{});
(function(a){var b=PS.Prelude,c=PS["Data.Monoid"],d=PS["Data.Foldable"];a.fontString=function(a){var f=a.value2;return d.intercalate(d.foldableArray)(c.monoidString)(" ")([d.fold(d.foldableMaybe)(c.monoidString)(f.style),d.fold(d.foldableMaybe)(c.monoidString)(f.variant),d.fold(d.foldableMaybe)(c.monoidString)(f.weight)])+(" "+(b.show(b.showInt)(a.value1)+("px "+a.value0)))}})(PS["Graphics.Drawing.Font"]=PS["Graphics.Drawing.Font"]||{});
(function(a){var b=PS.Prelude,c=PS["Data.List"],d=PS["Data.Maybe"],e=PS["Data.Foldable"],f=PS["Control.Monad"],g=PS["Control.Monad.Eff"],h=PS["Graphics.Canvas"],k=PS.Color,m=PS["Graphics.Drawing.Font"],n=PS.Math,p=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),l=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),r=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};
return a}(),t=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),v=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),w=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),x=function(){function a(b,c,d,e,g){this.value0=b;this.value1=c;this.value2=d;this.value3=e;this.value4=g}a.create=function(b){return function(c){return function(d){return function(e){return function(g){return new a(b,
c,d,e,g)}}}}};return a}(),C=function(){function a(b){this.value0=b}a.create=function(b){return new a(b)};return a}(),y=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),z=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),A=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),
D=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),G=function(){function a(b,c){this.value0=b;this.value1=c}a.create=function(b){return function(c){return new a(b,c)}};return a}(),H=A.create,I=b.flip(v.create);a.render=function(a){var d=function(q){if(q instanceof p&&q.value1 instanceof c.Nil)return b["return"](g.applicativeEff)(b.unit);if(q instanceof p&&q.value1 instanceof c.Cons)return function(){h.moveTo(a)(q.value1.value0.x)(q.value1.value0.y)();
e.for_(g.applicativeEff)(c.foldableList)(q.value1.value1)(function(b){return h.lineTo(a)(b.x)(b.y)})();return f.when(g.monadEff)(q.value0)(b["void"](g.functorEff)(h.closePath(a)))()};if(q instanceof l)return b["void"](g.functorEff)(h.rect(a)(q.value0));if(q instanceof r)return b["void"](g.functorEff)(h.arc(a)({x:q.value0.x,y:q.value0.y,r:q.value0.r,start:0,end:2*n.pi}));if(q instanceof t)return e.for_(g.applicativeEff)(c.foldableList)(q.value0)(d);throw Error("Failed pattern match at Graphics.Drawing line 312, column 3 - line 313, column 3: "+
[q.constructor.name]);},E=function(b){return function(){e.for_(g.applicativeEff)(e.foldableMaybe)(b.color)(function(b){return h.setShadowColor(k.cssStringHSLA(b))(a)})();e.for_(g.applicativeEff)(e.foldableMaybe)(b.blur)(function(b){return h.setShadowBlur(b)(a)})();return e.for_(g.applicativeEff)(e.foldableMaybe)(b.offset)(function(b){return function(){h.setShadowOffsetX(b.x)(a)();return h.setShadowOffsetY(b.y)(a)()}})()}},F=function(b){return function(){e.for_(g.applicativeEff)(e.foldableMaybe)(b.color)(function(b){return h.setStrokeStyle(k.cssStringHSLA(b))(a)})();
return e.for_(g.applicativeEff)(e.foldableMaybe)(b.lineWidth)(function(b){return h.setLineWidth(b)(a)})()}},B=function(b){return e.for_(g.applicativeEff)(e.foldableMaybe)(b.color)(function(b){return h.setFillStyle(k.cssStringHSLA(b))(a)})},u=function(f){if(f instanceof v)return b["void"](g.functorEff)(h.withContext(a)(function(){B(f.value1)();return h.fillPath(a)(d(f.value0))()}));if(f instanceof w)return b["void"](g.functorEff)(h.withContext(a)(function(){F(f.value1)();return h.strokePath(a)(d(f.value0))()}));
if(f instanceof C)return e.for_(g.applicativeEff)(c.foldableList)(f.value0)(u);if(f instanceof y)return b["void"](g.functorEff)(h.withContext(a)(function(){h.scale(f.value0)(a)();return u(f.value1)()}));if(f instanceof z)return b["void"](g.functorEff)(h.withContext(a)(function(){h.translate(f.value0)(a)();return u(f.value1)()}));if(f instanceof A)return b["void"](g.functorEff)(h.withContext(a)(function(){h.rotate(f.value0)(a)();return u(f.value1)()}));if(f instanceof D)return b["void"](g.functorEff)(h.withContext(a)(function(){d(f.value0)();
h.clip(a)();return u(f.value1)()}));if(f instanceof G)return b["void"](g.functorEff)(h.withContext(a)(function(){E(f.value0)();return u(f.value1)()}));if(f instanceof x)return b["void"](g.functorEff)(h.withContext(a)(function(){h.setFont(m.fontString(f.value0))(a)();B(f.value3)();return h.fillText(a)(f.value4)(f.value1)(f.value2)()}));throw Error("Failed pattern match at Graphics.Drawing line 262, column 1 - line 319, column 40: "+[f.constructor.name]);};return u};a.rotate=H;a.translate=function(a){return function(b){return z.create({translateX:a,
translateY:b})}};a.scale=function(a){return function(b){return y.create({scaleX:a,scaleY:b})}};a.filled=I;a.lineWidth=function(a){return{color:d.Nothing.value,lineWidth:new d.Just(a)}};a.fillColor=function(a){return{color:new d.Just(a)}};a.rectangle=function(a){return function(b){return function(c){return function(d){return new l({x:a,y:b,w:c,h:d})}}}}})(PS["Graphics.Drawing"]=PS["Graphics.Drawing"]||{});
(function(a){var b=PS["Data.Maybe"],c=PS["Graphics.Drawing"],d=PS["Graphics.Canvas"],e=PS.Flare;a.runFlareDrawing=function(a){return function(g){return function(h){return function(){var k=d.getCanvasElementById(g)();if(k instanceof b.Just){var m=d.getContext2D(k.value0)(),n=d.getCanvasWidth(k.value0)(),p=d.getCanvasHeight(k.value0)();return e.runFlareWith(a)(function(a){return function(){d.clearRect(m)({x:0,y:0,w:n,h:p})();return c.render(m)(a)()}})(h)()}throw Error("Failed pattern match at Flare.Drawing line 26, column 40 - line 37, column 33: "+
[k.constructor.name]);}}}}})(PS["Flare.Drawing"]=PS["Flare.Drawing"]||{});
(function(a){var b=PS.Prelude,c=PS.Flare,d=PS["Flare.Drawing"],e=PS["Graphics.Drawing"],f=PS["Control.Apply"],g=PS.Color,h=function(a){if(0>=a||1===a)return 1;if(b.otherwise)return h(a-1)+h(a-2)|0;throw Error("Failed pattern match at Main line 11, column 1 - line 16, column 1: "+[a.constructor.name]);},k=b["<$>"](c.functorUI)(h)(c["int"]("Fibonnaci")(3)),m=b["<$>"](c.functorUI)(b.show(b.showInt))(k),n=function(a){return function(b){return function(c){return e.filled(e.fillColor(g.hsl(a)(.8)(.4)))(e.rectangle(50)(50)(b)(c))}}},p=
f.lift3(c.applyUI)(n)(c.numberSlider("Hue")(0)(360)(1)(140))(c.numberSlider("Side H")(2)(145)(10)(25))(c.numberSlider("Side V")(2)(145)(10)(25));a.main=function(){c.runFlare("Multiplication")("Output")(m)();return d.runFlareDrawing("Graphics")("GraphOut")(p)()};a.uiG=p;a.coloredCircle=n;a.ui=m;a["fib'"]=k;a.fib=h})(PS.Main=PS.Main||{});PS.Main.main();
